name: flutter_svga
description: "A Flutter package for rendering SVGA animations with dynamic customization, smooth playback, and high performance."
version: 0.0.5
homepage: https://github.com/5alafawyyy/flutter_svga
repository: https://github.com/5alafawyyy/flutter_svga

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.2
  http: ^1.3.0
  path_drawing: ^1.0.1
  protobuf: ^3.1.0
  audioplayers: ^6.1.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

